### ISSUE TITLE
Unable to find suitable version for polymer

### ISSUE THREAD

**Issue by oneezy** [samiheikki/Polymer-scroll-progress#2]
Apparently all you have to do is update your bower.json to version ^1.4.0 w/ the carrot and it will install properly for everyone.

"dependencies": { "polymer": "^1.4.0" },

**Comment by samiheikki** [comment]
[https://github.com/samiheikki/scroll-progress/commit/891acbc8db643085fc3438db28de8dcacb002d90](https://github.com/samiheikki/scroll-progress/commit/891acbc8db643085fc3438db28de8dcacb002d90) Closes this
